### PR TITLE
Fixed support for custom activity dialog fragment

### LINKED ISSUE #35: Custom Activity dialog cannot be dismissed on API 19
Fix compatibility of the fragment for lower API levels

### PR DESCRIPTION
**Pull request by jkoryf**
Fixes #35

### CODE REVIEW

File: app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java [hunk 1]
```diff
@@ -73,8 +75,19 @@ public static CustomActivityCreatorFragment newInstance(LatLng coordinates, Date
         return frag;
     }
 
+    // For compatibility we should include the deprecated method too
+    @Override
+    public void onAttach(Activity context) {
+        System.out.println("context is "+context);
```
Comment (emaccaull) [inline app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java]: I think this is debug code? Can you use Log.d() if you want to keep it?

File: app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java [hunk 2]
```diff
@@ -73,8 +75,19 @@ public static CustomActivityCreatorFragment newInstance(LatLng coordinates, Date
...
+        super.onAttach(context);
+        if (context instanceof OnAddCustomActivityListener){
+            this.listener = (OnAddCustomActivityListener) context;
+        }
+    }
+
     @Override
     public void onAttach(Context context) {
+        System.out.println("context is "+context);
```
Comment (emaccaull) [inline app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java]: Same here.

File: app/src/main/java/com/paranoidandroid/journey/legplanner/activities/PlannerActivity.java [hunk 3]
```diff
@@ -383,12 +383,10 @@ public void addFromBookmarksPressed(View v) {
     public void addCustomActivityPressed(View v) {
         Day day = getDayPlannerFragment().getSelectedDay();
         Destination dest = day.getLeg().getDestination();
-        FragmentManager fragmentManager = getSupportFragmentManager();
+        FragmentManager fragmentManager = getFragmentManager();
```
Comment (emaccaull) [inline app/src/main/java/com/paranoidandroid/journey/legplanner/activities/PlannerActivity.java:386]: Is it safe to use this when inheriting from AppCompatActivity? I remember Nathan saying it could cause problems to use getFragmentManager() in this case.

Comment (jkoryf) [reply app/src/main/java/com/paranoidandroid/journey/legplanner/activities/PlannerActivity.java:386]: I believe it's OK to use android.app.FragmentManager if the fragments that you are going to load with it are native fragments (i.e. android.app.Fragment). 
I had to implement the CustomActivityCreatorFragment dialog as an android.app.DialogFragment instead of its support equivalent, in order to support the PlaceAutocompleteFragment inside. 
Its equivalent support option, SupportPlaceAutocompleteFragment, was having a lot of issues during my tests on API 19.

File: app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java (hunk 1 above)
Comment (jkoryf) [reply app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java]: The PR is now updated to remove this line

File: app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java (hunk 2 above)
Comment (jkoryf) [reply app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/CustomActivityCreatorFragment.java]: The PR is now updated to remove this line

**Review by emaccaull — APPROVED** [review]
:+1:  Looks good!

**Review by jpushkarskaya — APPROVED** [review]
