### PR TITLE
Fix last day not showing in planner

### LINKED ISSUE #41: Planner tabs do not show the last day of the journey

### PR DESCRIPTION
**Pull request by jkoryf**
Fixes #41

### CODE REVIEW

File: app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/DayPlannerFragment.java [hunk 1]
```diff
@@ -146,7 +146,7 @@ public Day getSelectedDay() {
         List<Day> days = new ArrayList<>();
         Calendar calendar = new GregorianCalendar();
         calendar.setTime(leg.getStartDate());
-        while (calendar.getTime().before(leg.getEndDate()))
+        while (calendar.getTime().before(leg.getEndDate()) || calendar.getTime().equals(leg.getEndDate()))
```
Comment (emaccaull) [inline app/src/main/java/com/paranoidandroid/journey/legplanner/fragments/DayPlannerFragment.java]: You could do:

    while (!calendar.getTime().after(leg.getEndDate()))

but this works fine.

**Review by emaccaull — APPROVED** [review]
:+1:

**Review by jpushkarskaya — APPROVED** [review]
